spring.application.name=oldCar

# H2 데이터베이스 설정
spring.datasource.url=jdbc:h2:mem:cardb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA 하이버네이트 테이블 자동 생성 및 SQL 로그
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# H2 웹 콘솔 활성화 (시연용)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console